### ISSUE TITLE
error status code 12502 on authentication

### ISSUE THREAD

**Issue by M4rc0b** [Abedalkareem/games_services#107]
It's been a few days I'm getting this error, status code 12502 or 12501 in production.
I don't know why, I have not change anything in configuration, maybe it depends to last version? 
Thanks!

Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(failed_to_authenticate, Something went wrong Status{statusCode=unknown status code: 12502, resolution=null}, null, null)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:315)
       at MethodChannelGamesServices.signIn(game_services_platform_impl.dart:87)
       at GameAuth.signIn(game_auth.dart:10)

**Comment by RaulSangosto** [comment]
Hello!, acording to this resource https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInStatusCodes

public static final int SIGN_IN_CANCELLED
The sign in was cancelled by the user. i.e. user cancelled some of the sign in resolutions, e.g. account picking or OAuth consent.

Constant Value: 12501
public static final int SIGN_IN_CURRENTLY_IN_PROGRESS
A sign in process is currently in progress and the current one cannot continue. e.g. the user clicks the SignInButton multiple times and more than one sign in intent was launched.

Constant Value: 12502

Hope it helps
