### ISSUE TITLE
Feature Request: silentSignIn Function

### ISSUE THREAD

**Issue by mgazisalik** [Abedalkareem/games_services#117]
**Description:**
Users with low internet connections are experiencing delays when Google Play services force them to sign in upon app launch. This disrupts gameplay and negatively impacts the user experience.

**Feature Request:**
Please consider implementing a silentSignIn function. This would attempt to sign users in without UI intervention, especially for those who've already signed in before. It would help in reducing delays and enhancing the user experience for those with slower internet.

**Comment by Abedalkareem** [comment]
Hi,
On Android, it's doing silentSignIn; if it fails, it's calling explicitSignIn.
