### ISSUE TITLE
Specify namespace

### ISSUE THREAD

**Issue by xxjonesriderxx** [Abedalkareem/games_services#118]
When using Gradle 8.0.2 im getting following issue: 

* What went wrong:
A problem occurred configuring project ':games_services'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

     android {
         namespace 'com.example.namespace'
     }

     If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

Please simply add your namespace

**Comment by Abedalkareem** [comment]
This issue fixed in release version 3.0.3
