### ISSUE TITLE
Unable to build the Android plugin

### ISSUE THREAD

**Issue by alexeystrakh** [Abedalkareem/games_services#12]
The issue is that autogenerated flutter class `GeneratedPluginRegistrant` is trying to create an instance of the plugin without parameter and even though the parameter is optional, it still expected by the generated file.

The issue has been fixed in this PR: https://github.com/Abedalkareem/games_services/pull/11

**Comment by Abedalkareem** [comment]
HI @alexeystrakh,
This issue actually reported multiple times.
Thank you for the fix!
