### ISSUE TITLE
iOS17 support

### ISSUE THREAD

**Issue by TatsuyaSagara** [Abedalkareem/games_services#121]
Does it support iOS17?

If you log into Game Center, run the sample and press the "Is signedIn" button, you will see false.

Since you are logged into Game Center, true should be displayed.

Pressing the "Is signedIn" button raises the following exception

Unhandled Exception: PlatformException(failed_to_authenticate, The requested operation could not be completed because the local player has not been The requested operation could not be completed because local player has not been authenticated.)

**Comment by theLee3** [comment]
Ensure that your project has the Game Center entitlement enabled in Xcode.

**Comment by M4rc0b** [comment]
Hi, I'm having the same problem. Yesterday, I managed to resolve it somehow after many attempts. Today, I'm facing the same issue with another app. Maybe it depends on iOS, but I really don't know.

**Comment by theLee3** [comment]
Are you experiencing the problem on Simulator or physical devices?

**Comment by M4rc0b** [comment]
I am experiencing the problem on both the Simulator and physical devices. Today, after trying on a different device and going through various steps like removing, clearing, and restarting, the authentication finally worked.

**Comment by theLee3** [comment]
Hmm... it may very well be an iOS issue then. We simply access the `isAuthenticated` getter on the `GKLocalPlayer` object, which hasn't changed.

As far as I know, the only thing that has changed is the Game Center entitlement mentioned above. It was introduced with iOS 15 and required to upload a release build to the App Store, but I believe with iOS 17 it is now required even when testing on the device. I have not been able to verify this in any documentation, but when I was testing, I was unable to login before adding the entitlement.

**Comment by theLee3** [comment]
I will be working on removing deprecated iOS methods for the 4.0 release soon though. So IF I can reproduce this issue and learn any more, I will report back on this thread.

**Comment by TatsuyaSagara** [comment]
@theLee3 I checked the tutorial again. Game Center entitlements were not enabled in Xcode.Thank you for letting me know.

**Comment by Abedalkareem** [comment]
@TatsuyaSagara 

I just faced the same issue, as you mentioned you have to enable Game Center from the Singing and Capabilities tab.

![image](https://github.com/Abedalkareem/games_services/assets/14274852/ca031bd5-f5db-4ff1-83d4-0e2dcde4861b)
