### ISSUE TITLE
How to get rid of this stupid consent screen!

### ISSUE THREAD

**Issue by mrgzi** [Abedalkareem/games_services#132]
Sorry for the bad title. I couldn't solve this issue for about 3 months. Here is the thing that I want to get rid of;
<p float="left">
<img src="https://github.com/Abedalkareem/games_services/assets/11049295/021fcefd-249d-47b7-a3a2-d34958fe6be5" width=30% height=30%>
<img src="https://github.com/Abedalkareem/games_services/assets/11049295/171b5fde-e455-42e8-a996-0ffa5044e090" width=30% height=30%>
<img src="https://github.com/Abedalkareem/games_services/assets/11049295/ff649f48-4922-4d24-9155-259bb85bdc52" width=30% height=30%>
</p>

At first I had 3 scopes, then I deleted two of them and just left the games scope. I waited one month for the google cloud safety team approvement. Then the issue was still continue, I decided to delete the last scope too. And waited one more month :( Finally there is no scope!
<p float="center">
<img src="https://github.com/Abedalkareem/games_services/assets/11049295/84e53d98-f9e5-4c69-ba47-0cc3246cebb6" width=50% height=50%>
</p>

There is no need to scary user, why google doing that? I talked with both Google Play and Google cloud support. Google Play support couldn't help this, but Google Cloud support repeating the same thing;

> Please make sure to delete the non sensitive scope (https://www.googleapis.com/auth/games_lite) from the codebase of your app.

I looked at my codebase and the package codebase, it seems fine. Here is my code related to sign-in;

```dart

  /// Signs into the underlying games service.
  initialize() async {
    try {
      await gs.GamesServices.signIn();
      // The API is unclear so we're checking to be sure. The above call
      // returns a String, not a boolean, and there's no documentation
      // as to whether every non-error result means we're safely signed in.
      await gs.GamesServices.isSignedIn;
    } catch (e) {
      _log.severe('Cannot log into GamesServices: $e');
    }
  }
```

After a while I realized it's because of saved games enabled in play games project. 
 
<img alt="Screenshot 2023-12-08 at 00 43 38" src="https://github.com/Abedalkareem/games_services/assets/11049295/908e1d0f-3492-4655-a24b-9c7a0308fbb2">

So the weird thing is that I don't even use this feature and will never use it, instead i am planning saving feature in my own backend side. For this, I just need **player id**. But, they don't allow me to turn off saved games feature.

I decided to delete current play games project and create new one but didn't allow me to use same google cloud project :( Probably the best solution was to create another google cloud project and started to implement it. While doing this I came across this info;

> Note: Make sure that the consent screen is available to everyone that the game is available to. The final list of scopes needs to include games, games_lite, and drive.appdata; none of these scopes will require app verification. We recommend publishing the consent screen immediately. If that is not possible, you can make the consent screen available to testers to allow them to sign-in to the game.

But in the new google cloud project, when I creating consent screen; I can't see these scopes **"games, games_lite, and drive.appdata"** . If I can't enable at least "games" scope, users will not be able to authenticate.

There is similiar issue on stackoverflow: https://stackoverflow.com/questions/54723655/google-games-scary-permission-for-signin-create-edit-and-delete-your-google

**Summerize the story**; I enabled saved games in the play games services project when I created. Now I can't get rid of. I am stuck in a limited information on the internet.

**Comment by theLee3** [comment]
This is unfortunately how the original Play Games Services (PGS) worked. As of games_services 4.0.0, we use PGS v2. The sign-in flow is much smoother and presents no consent screen, even if you are using the saved games feature.

Please update the games_services version in pubspec.yaml:
```
games_servcies: ^4.0.0
```

NOTE: Sign-in occurs automatically when your app launches. This is handled at the OS level, and you cannot stop it. Your app also cannot sign the player out anymore. Account settings and behavior must be handled by the user in system settings or the Play Games app.

**Comment by mrgzi** [comment]
@theLee3 Yes, It works! Thank you a lot 👍
