### ISSUE TITLE
[Android] score not changing after 3 points

### ISSUE THREAD

**Issue by erperejildo** [Abedalkareem/games_services#134]
In my game, there are 3 modes in which you can submit 1, 2 and 3 points. I can play the first 2 and get 3 points, or the last one and get 3 points the first time, but it's not going up after that.

I have tested this with 2 different accounts and 2 phones. Emulator/real and debug/release.

Demo: https://play.google.com/store/apps/details?id=com.drodriguez.time_tap

![image](https://github.com/Abedalkareem/games_services/assets/5629919/fcbae238-2400-4762-91ac-4bc25d4897c7)

![image](https://github.com/Abedalkareem/games_services/assets/5629919/1ff8485a-1d64-4ee3-87d1-6e90937729be)

![image](https://github.com/Abedalkareem/games_services/assets/5629919/71aacf19-91f2-4de4-82bc-55d8fec984d4)

**Comment by theLee3** [comment]
Are you only passing a max score of 3 to `Scores.submit`? This method submits the actual score you pass to it. It does not increment the online leaderboard score, as this is not possible.

**Comment by erperejildo** [comment]
> Are you only passing a max score of 3 to `Scores.submit`? This method submits the actual score you pass to it. It does not increment the online leaderboard score, as this is not possible.

I'm passing either 1, 2 or 3. So if I pass:
- 1: I'll have 1 point in total
- 1 (again): I'll have 2 points in total
- 1 (again): I'll have 3 points in total
- 1 (again): it doesn't change

How should this be sent?

**Comment by theLee3** [comment]
It should go something like this.

```dart
var currentScore = 0;

void gamePlayLoop() {
    while (gameIsBeingPlayed) {
        // something happens to implement score
        currentScore++;
    }

    // gameplay loop ends from game over, round over, etc.
   submitScore();
}

void submitScore() {
    // update player's score on leaderboard
    Leaderboards.submitScore(
        Score(
            androidLeaderboardID: 'leaderboard_ID',
            value: currentScore,
        );
    );
}

**Comment by erperejildo** [comment]
> It should go something like this.
> 
> ```dart
> var currentScore = 0;
> 
> void gamePlayLoop() {
>   while (gameIsBeingPlayed) {
>     // something happens to implement score
>     currentScore++;
>   }
> 
>   // gameplay loop ends from game over, round over, etc.
>   submitScore();
> }
> 
> void submitScore() {
>   // update player's score on leaderboard
>   Leaderboards.submitScore(
>     Score(
>       androidLeaderboardID: 'leaderboard_ID',
>       value: currentScore,
>     );
>   );
> }
> ```

but that's what I have. I only send score when game is ended and this can be 1, 2 or 3. That's all.
If you start a new game, you will send the same type of score and it doesn't go up.

I'm not sending the score multiple times within the same game, just once.

**Comment by theLee3** [comment]
but it will not increase beyond 3 with that logic. If your max score is 3, then the most the leaderboard can show is 3. If you were to send 4, it would show 4. Send 1527 for 1527 on the leaderboard, etc. It seems that you have never sent anything other than a 1 2 or 3 and therefore it can't go beyond 3. A leaderboard is for current high score, not incremental score over time.

Also of note, you cannot go down from a score on a leaderboard. So once you set it to 3, you can't go back down to 2. You can use time scopes to create recurring leaderboards that "reset" on a given interval. Otherwise, if you send a lower score than the one on the leaderboard, it is simply ignored.

**Comment by theLee3** [comment]
Do me a favor and try sending a score higher than 3, just hard-coded. If you leaderboard is in draft, you can easily remove the score if you don't want it there after.

```dart
Leaderboards.submitScore(
    Score(
      androidLeaderboardID: 'leaderboard_ID',
      value: 4,
    );
  );
```

If the leaderboard is updated, this confirms that the issue is in your scoring logic.

**Comment by erperejildo** [comment]
Then the solution is this:

```
Future<void> submitScore(int value) async {
    dynamic currentScore = await getPlayerScore();
    currentScore ??= 0;

    await Leaderboards.submitScore(
        score: Score(
      androidLeaderboardID: androidLeaderboardId,
      value: currentScore + value,
    ));
  }
```
