### ISSUE TITLE
[Android] Cannot use snapshots without enabling the 'Saved Game' feature in the Play console

### ISSUE THREAD

**Issue by erperejildo** [Abedalkareem/games_services#135]
The error seems pretty self-explanatory, but I have this already enabled. Google's documentation says it can take up to 24h to activate, but I activated this days ago and I constantly get this error, no matter how long I wait. Looking in google for extra configuration, I don't find anything else.

![image](https://github.com/Abedalkareem/games_services/assets/5629919/384a6e51-1df6-420b-8843-bfc273ec5fd6)

![image](https://github.com/Abedalkareem/games_services/assets/5629919/52f8be9d-ddf5-4180-9598-8bcf7ce7a5c3)

**Comment by erperejildo** [comment]
any update?

**Comment by erperejildo** [comment]
> Be sure you have added the drive.appdata scope to your OAuth consent screen via the GCP console, under APIs & Services.

![image](https://github.com/Abedalkareem/games_services/assets/5629919/a72e2e30-553c-4e5c-ac48-f809c6fc29ca)

but the OAuth consent screen wasn't published. Is that the problem? I was testing on emulator

**Comment by theLee3** [comment]
No this should not be a problem. Is everything working on that build except saved games? Try toggling the saved games off on Google Play Console (make sure the change is published for the Game Project). Then toggle it back on and see if it resolves the issue.

**Comment by erperejildo** [comment]
> No this should not be a problem. Is everything working on that build except saved games? Try toggling the saved games off on Google Play Console (make sure the change is published for the Game Project). Then toggle it back on and see if it resolves the issue.

leaderboard, score, achievements... everything work.
I tried already to enable/disable it. What I didn't do is wait like hours/days before enabling it back

**Comment by erperejildo** [comment]
It is:

![image](https://github.com/Abedalkareem/games_services/assets/5629919/fcbfdc11-8a86-42d5-b00e-7af17fa56bf0)

Google Drive API is not receiving anything:

![image](https://github.com/Abedalkareem/games_services/assets/5629919/70024bd7-e900-4cf9-a6d0-b0668b8d5d75)

![image](https://github.com/Abedalkareem/games_services/assets/5629919/4a7bed01-8249-42fa-b37c-1b002950c5e3)

**Comment by theLee3** [comment]
Select the credentials tab on the Google Drive API view. And see which clients have access to it.

**Comment by erperejildo** [comment]
that's correct, the ones I created for this project:

![image](https://github.com/Abedalkareem/games_services/assets/5629919/d7fcc10f-b0ca-46c9-8b14-f0dfe0c62ea8)

**Comment by theLee3** [comment]
I would reach out to Google support as it seems everything is configured correctly. The fact that you're being told it isn't turned on for the project points to an issue on their end.

**Comment by theLee3** [comment]
First, try clearing the data for Play Games Services under the app settings and try again.

**Comment by theLee3** [comment]
A couple of more thoughts on what may cause this before you contact Google support.

1. The device has not had a network connection since the setting has been activated.
2. The version of Play Games Services is sufficiently outdated so as to not properly handle v2 scopes.

IDK, just brainstorming here.

**Comment by erperejildo** [comment]
I tried all of that but not sure why it's not working. I'll try again in a few days

**Comment by erperejildo** [comment]
I tried again today and it seems to work. They say 24h after you enable it but it happened like a week or so for me. 

Anyway... working now.
