### ISSUE TITLE
Firebase auth

### ISSUE THREAD

**Issue by erperejildo** [Abedalkareem/games_services#145]
Not sure if this could be achieved by using this package but I don't find any other documentation related to Flutter. I also found a reference to this package here: https://github.com/firebase/flutterfire/issues/5303

In my app I can authenticate using Google but I'd like to avoid this and use the actual GPG user, which is already logged in.

How can I do this?

**Comment by theLee3** [comment]
I have submitted a feature request to the flutterfire repo [here](https://github.com/firebase/flutterfire/issues/12190). I have implemented a method that returns the `server_auth_code`, so once they implement the `PlayGamesAuthProvider`, this will be simple.

Hop over there and give it an upvote.

**Comment by theLee3** [comment]
The alternative for the time being is to use the [REST API](https://developers.google.com/games/services/android/offline-access#exchange_the_server_auth_code_for_an_access_token_on_the_server) to get the `UserCredential` and go from there.

**Comment by theLee3** [comment]
I have also submitted a [feature request](https://github.com/firebase/flutterfire/issues/12191) for Game Center authentication via the `GameCenterAuthProvider`. That seemingly requires no changes to the games_services plugin.

**Comment by erperejildo** [comment]
Thanks @theLee3. 
However, there is no rush from my side to implement something else in the meantime.

**Comment by theLee3** [comment]
`firebase_auth` has added Play Games and Game Center auth in version 4.17.0.

You can build from the above PR to use now. `games_services` 4.1.0 will release soon with this functionality.

To sign in with Play Games:
```dart
final authCode = await GameAuth.getAuthCode(clientID);
if (authCode != null) {
  final userCredential = await FirebaseAuth.instance.signInWithCredential(
    PlayGamesAuthProvider.credential(serverAuthCode: authCode),
  );
}
```

To sign in with Game Center:
```dart
final userCredential = await FirebaseAuth.instance
  .signInWithCredential(GameCenterAuthProvider.credential());
```

**Comment by erperejildo** [comment]
Cool. I'll update as soon as it get released.
Thanks

**Comment by erperejildo** [comment]
Any idea when it will be released?

**Comment by Abedalkareem** [comment]
@erperejildo 

Hi
[4.0.1](https://github.com/Abedalkareem/games_services/releases/tag/4.0.1) just got released with this change.
