### ISSUE TITLE
Get Player Rank on A Laderboard

### ISSUE THREAD

**Issue by francichecco** [Abedalkareem/games_services#147]
Actually the Player class has only this method 

```
getPlayerScore(
    {dynamic iOSLeaderboardID = "",
    dynamic androidLeaderboardID = ""}
)
```

with that I can retrive the player score on a laderboard.

**Could you add the method to retrive the player ranking on a laderboard ?** 
`public abstract [String] getDisplayRank () <----------------------------------------- ADD THIS PLS`

https://developers.google.com/android/reference/com/google/android/gms/games/leaderboard/LeaderboardScore

**Comment by theLee3** [comment]
@Abedalkareem We could easily return a `LeaderboardScoreData` object that would contain the score, rank * more. Should we do so from `getPlayerScore` or create a new method `getPlayerScoreData` and encourage its use going forward?

There is no need to provide both individually as we are already retrieving the object with all of this information to just return the score value, and it would be wasteful to make extra network calls for data we have already retrieved.

**Comment by egonbeermat** [comment]
I actually implemented this about a year ago in a local modified version of this package, a method to retrieve a players score rank on leaderboards. I wanted to retrieve specifically by span - today, this week, all time -  but `getPlayerScore` is only fixed to allTime and, not wanting to mess with an existing method given I'm not very familiar with native development, I cut and paste code into a new method `getPlayerScoreObject` that returns a fully populated `LeaderboardScoreData`, including the rank. 

I've not done an update to an existing repo before, but happy to share the code somehow for you to evaluate to incorporate.

**Comment by egonbeermat** [comment]
I resolved the conflict (I think! My first ever PR on another repo)

**Comment by Abedalkareem** [comment]
@egonbeermat 
That's awesome! Congrats on your first PR!


Thank you!

**Comment by egonbeermat** [comment]
@theLee3 Thanks! Glad it all appears to work for you! I understand completely about that pesky personal stuff :)

**Comment by theLee3** [comment]
Added in #155
