### ISSUE TITLE
App Crash: LICENSE_CHECK_FAILED

### ISSUE THREAD

**Issue by orkun1675** [Abedalkareem/games_services#149]
Hello, my app submission has recently been denied as it crashed when the Android review team was manually testing it.

Based on what I can see from the Crashlytics logs is that  the games_services plugin was what caused this. Please see the stacktrace during the crash below:

<img width="1126" alt="Screenshot 2024-01-22 at 9 50 33 AM" src="https://github.com/Abedalkareem/games_services/assets/2564599/39b82d61-f2bc-445f-b20b-9c453a588d65">

My app does have [anti-piracy](https://developers.google.com/games/services/android/antipiracy) turned on. And I imagine the Android review team haven't added themselves to the approved testers list. So it is expected that they will be getting `LICENSE_CHECK_FAILED` code for all Play Games requests.

**Comment by theLee3** [comment]
This is likely a configuration issue. Have you successfully run a release build on a device, or have you only run debug builds?

A few things to check:

1. Is the game published under Play Games Services Configuration? This is necessary for non-testers to have access to the features (including the Play Store testers).
2. Do you request internet permission in AndroidManifest.xml?
3. Are all client credentials configured correctly under Play Games Configuration?

**Comment by orkun1675** [comment]
The app and Play Games features are working as expected for internal testers. I create publish test builds via Play Console and declare internal testers via the same UI. I also add these tester emails to the Play Games testers list.

The linked anti-piracy article states that the user will get `LICENSE_CHECK_FAILED` if they are not listed in the Play Games tester list. I was not able to reproduce this, though I didn't try with a fresh Gmail account.

In either case, the app should not be crashing if this status code is returned from GMS, right?

**Comment by theLee3** [comment]
Ah my bad. You are correct. #138 does address this issue.
