### ISSUE TITLE
[Android] Failed to get the score

### ISSUE THREAD

**Issue by erperejildo** [Abedalkareem/games_services#161]
```
Future getPlayerScore() async {
    try {
      return await Player.getPlayerScore(
          androidLeaderboardID: androidLeaderboardId);
    } catch (error) {
      debugPrint(error.toString());
      return null;
    }
  }
```

code: `failed_to_get_score`
message: Failed to get the score

Why is this happening? Could we get a better message description?

**Comment by Abedalkareem** [comment]
We usually return the message we get from Android/iOS side, in this case we got success but there was no data. I think this case should not happen.
Which platform is this?

**Comment by erperejildo** [comment]
I'm not facing this again so not sure what the problem was exactly. I'll reopen in case I get it again
