### ISSUE TITLE
Unable To Load Achievements on s24 ultra

### ISSUE THREAD

**Issue by mrmhthegreat** [Abedalkareem/games_services#162]
It say Login But  no Achievements is loaded
i work fine on andriod 8 i test but not on andriod 14

`GooglePlayServicesAvailability availability =
            await GoogleApiAvailability.instance
                .checkGooglePlayServicesAvailability(false);`
`      

        if (availability == GooglePlayServicesAvailability.success) {
          try {
            bool islogin = await GameAuth.isSignedIn;
            if (!islogin) {
              await GameAuth.signIn();
              islogin = await GameAuth.isSignedIn;
             }

`

           ` if (islogin) {
              toast("Login");
              try {
               final result = await Achievements.loadAchievements();

                debugPrint(result.toString());

                }on PlatformException catch (e) {
           

                debugPrint("loginf");
 
              } catch (e) {
                debugPrint("loginf");
         
              }`

**Comment by Abedalkareem** [comment]
Hi,
Can you share the logs after you do
`await GameAuth.signIn();`
?

**Comment by mrmhthegreat** [comment]
Thanks you just need to update Documention We also need to add tester on [OAuth consent screen]

![Capture](https://github.com/Abedalkareem/games_services/assets/90477458/a7e8db87-9e3c-4e4d-a42b-ff20b59c8e90)
