### ISSUE TITLE
Android: leaderboards.submitScore with score > 32bit limit returns error, doesn't submit

### ISSUE THREAD

**Issue by egonbeermat** [Abedalkareem/games_services#166]
Dart int is 64 bit, Play Games score value is Long (also 64 bits), but

`games_services/android/src/main/kotlin/com/abedalkareem/games_services/GamesServicesPlugin.kt:136` has:

`val score = call.argument<Int>("value") ?: 0`

**Int** in this case is 32 bits, and returns an error if the submitted value is greater than that. Can be solved by:

```
val scoreValue = call.argument<Any>("value")
var score = if (scoreValue is Long) scoreValue.toLong() else (scoreValue as Int).toLong()
//scoreValue will be Int for values that fit in 32 bit, hence the need for a conditional for typecasting
```
and changing `leaderboards.submitScore` score parameter to **Long**, instead of **Int**

I was wondering why my leaderboards for iOS have top scores of 6bn plus, but Android players couldn't seem to manage more than 2.147bn :)

**Comment by theLee3** [comment]
> I was wondering why my leaderboards for iOS have top scores of 6bn plus, but Android players couldn't seem to manage more than 2.147bn :)

So you're telling me iOS players aren't just that much better?? 😆 

Fix incoming. Thanks for your input.

**Comment by egonbeermat** [comment]
> So you're telling me iOS players aren't just that much better?? 😆

My entire world view has been shattered!
