### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by 45manu95** [Abedalkareem/games_services#174]
Hi! I was update my app and i got this error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':games_services:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 9m 27s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).

I think the error is due to a mismatch between the Java versions used for compiling Kotlin and Java code in this project. Specifically, the Kotlin compiler is configured to use Java 17, while the Java compiler is set to use Java 8.

I think the solutions is to update the build.gradle of the Affected Module (:games_services) in order to ensure that both the Kotlin and Java compilers use Java 17.

Example:
android {
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

**Comment by vintage** [comment]
It's been fixed some time ago through https://github.com/Abedalkareem/games_services/pull/168 but not yet released to the pub.dev

**Comment by theLee3** [comment]
Closing as this is fixed. @Abedalkareem Can we publish the latest to pub.dev soon?

**Comment by Abedalkareem** [comment]
@theLee3 

Thanks, Yes published now!
