### ISSUE TITLE
how to show this welcome banner ?

### ISSUE THREAD

**Issue by elmissouri16** [Abedalkareem/games_services#179]
```
import 'dart:async';
import 'package:flutter/services.dart';
import 'package:games_services/games_services.dart';
import 'package:legendary_leader/utils/talker_logger.dart';

class GamesManager {
  GamesManager._();
  static final GamesManager instance = GamesManager._();
  static bool isSignedIn = false;
  Future<void> signIn() async {
    try {
      if (!await GamesServices.isSignedIn){
        final results = await GamesServices.signIn();
        talker.debug('GamesManager.signIn', results);
        
     
      }
      isSignedIn = await GamesServices.isSignedIn;
     
    } on PlatformException catch (e) {
      talker.debug('GamesManager.signIn', e);
    }
  }
}

```
![image](https://github.com/user-attachments/assets/9f11d802-5ef1-4502-b075-a90ee46adfdc)

this is my code is there a special function to call to show it or its by default? i don't have game save enabled in my google play console so I wondering if this the case. thanks in advance

**Comment by theLee3** [comment]
This is shown by default on sign in. You are not required to do anything else.

**Comment by elmissouri16** [comment]
> This is shown by default on sign in. You are not required to do anything else. Nor can you show it by any other method.

thanks I figure it out just when the app wasn't  published on the Play Store wasn't showing until its published
