### ISSUE TITLE
[Android] showLeaderboards(), showAchievements() not working

### ISSUE THREAD

**Issue by mattdamon108** [Abedalkareem/games_services#18]
In iOS, it works perfectly. But in Android, nothing is working. I'm not sure that it gets authenticated or signed in when I call `GamesServices.signIn()`.

Is there any way to check or debug whether it has signed in? Or any troubleshoot tips for this issue? I read and read your medium article and other articles to set a configuration for games services.

**Comment by Abedalkareem** [comment]
Hi,
First thing before calling anything you need to sign in.
```GamesServices.signIn();```
then you can call any other method.

To get if there is an error from the method you can do this:
```
final result = await GamesServices.showAchievements();
debugPrint(result);
```
