### ISSUE TITLE
Error on iOS in version 0.2.1

### ISSUE THREAD

**Issue by javipacheco** [Abedalkareem/games_services#2]
I have upgraded to version 0.2.1 and I have a new error

```
Xcode's output:
↳
    === BUILD TARGET firebase_crashlytics OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/gadestudios/Development/flutter/.pub-cache/hosted/pub.dartlang.org/games_services-0.2.1/ios/Clas
    ses/GamesServicesPlugin.m:2:9: fatal error: 'games_services/games_services-Swift.h' file not found
    #import <games_services/games_services-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

Could you please help me?

Thank you in advance

**Comment by javipacheco** [comment]
I have this problem in my code. I would like to try your lib, I think that it's a really good lib for flutter

Could you please help me with this problem?

Thanks

**Comment by Abedalkareem** [comment]
Hi javipacheco.
I'm really sorry for the delay, but I was busy.
I fixed the issue with the 0.2.2 version. 
can you try now?

**Comment by javipacheco** [comment]
Sorry but I have a similar problem

```
    === BUILD TARGET FirebaseInstanceID OF PROJECT Pods WITH CONFIGURATION Release ===
    /Users/gadestudios/Development/flutter/.pub-cache/hosted/pub.dartlang.org/games_services-0.2.2/ios/Classe
    s/GamesServicesPlugin.m:2:9: fatal error: 'games_services/games_services-Swift.h' file not found
    #import <games_services/games_services-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

I did a `flutter clean` and `flutter build ios`

I think that I have all ok in my xCode project. Can it be a problem with my configuration?

I'm an Android dev, it's my first experience on iOS :-(

Thank you for your time

**Comment by Abedalkareem** [comment]
Hi
Can you please go to your flutter project, then iOS then delete the Pods folder and install then go back to your flutter project and update the plugins then run the app again?

**Comment by javipacheco** [comment]
I've tried to remove the "pod" directory and it doesn't work.

I have a question, where is the [games_services-Swift.h](https://github.com/Abedalkareem/games_services/blob/master/ios/Classes/GamesServicesPlugin.m#L2) file? I'm looking in your repository but I can't find it.

Should you have that file here?

**Comment by Abedalkareem** [comment]
It's something generated by Xcode.
Can you tell me what is the version of your Xcode? and did you try to run the example with the project?

because I'm trying to use the plugin and it's working fine.
if you can give me the following things so maybe I'll be able to replicate the issue:
-Xcode version.
-flutter version.

**Comment by javipacheco** [comment]
The example compiles fine, I can run the project, but the lib doesn't work in my app :-(

XCode Version: 11.0
Flutter Version: 1.9.1+hotfix.5

I've been reviewing my Xcode Project but I think that all is ok, but I've found the file in your project

```
workspaces find . -name "games_services-Swift.h" 
./games_services/example/build/ios/Debug-iphonesimulator/games_services/games_services.framework/Headers/games_services-Swift.h
```

but in my project I don't have `games_services.framework` folder on `ios/Debug-iphonesimulator/games_services/`, I have a `games_services.swiftmodule`

![Captura de pantalla 2019-11-16 a las 9 19 10](https://user-images.githubusercontent.com/456025/68990313-30f62680-0852-11ea-9065-9ca401a9f2f2.png)

In the left side your project and my project is in the right

any idea?

**Comment by javipacheco** [comment]
Finally, I have fixed the error using [this comment](https://github.com/flutter/flutter/issues/16049#issuecomment-382629492)

Thank you for your help!

**Comment by Abedalkareem** [comment]
That's amazing!
I'm sorry for the delay in response but I have a lot of work and I'm leaving the office late some times.
