### ISSUE TITLE
SignIn Error

### ISSUE THREAD

**Issue by co-in** [Abedalkareem/games_services#20]
E/Error   (13343): signInError
E/Error   (13343): com.google.android.gms.common.api.ApiException: 4: 4: 
E/Error   (13343): 	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source:4)
E/Error   (13343): 	at com.google.android.gms.common.internal.zai.zaf(Unknown Source:2)
E/Error   (13343): 	at com.google.android.gms.common.internal.zaj.onComplete(Unknown Source:6)
E/Error   (13343): 	at com.google.android.gms.common.api.internal.BasePendingResult.zaa(Unknown Source:172)
E/Error   (13343): 	at com.google.android.gms.common.api.internal.BasePendingResult.setResult(Unknown Source:131)
E/Error   (13343): 	at com.google.android.gms.auth.api.signin.internal.zzj.zzc(Unknown Source:5)
E/Error   (13343): 	at com.google.android.gms.auth.api.signin.internal.zzt.dispatchTransaction(Unknown Source:6)
E/Error   (13343): 	at com.google.android.gms.internal.auth-api.zzd.onTransact(Unknown Source:12)
E/Error   (13343): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
E/Error   (13343): 	at android.os.Binder.execTransact(Binder.java:994)
I/flutter (13343): PlatformException(error, 4: 4: , null)

**Comment by Abedalkareem** [comment]
Hi, 
Please check:
https://stackoverflow.com/questions/50527420/google-play-service-game-silent-login-error-com-google-android-gms-common-api-a
https://stackoverflow.com/questions/55873705/google-play-games-services-signin-error-apiexception-4

**Comment by msarkrish** [comment]
I'm also facing the same problem brother. I saw above stackoverflow answer. Whether i need to create Firebase project to solve my problem? because in the above answer the user using firebase in his project. I'm not using firebase in my application.

**Comment by msarkrish** [comment]
> 
> 
> E/Error (13343): signInError
> E/Error (13343): com.google.android.gms.common.api.ApiException: 4: 4:
> E/Error (13343): at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source:4)
> E/Error (13343): at com.google.android.gms.common.internal.zai.zaf(Unknown Source:2)
> E/Error (13343): at com.google.android.gms.common.internal.zaj.onComplete(Unknown Source:6)
> E/Error (13343): at com.google.android.gms.common.api.internal.BasePendingResult.zaa(Unknown Source:172)
> E/Error (13343): at com.google.android.gms.common.api.internal.BasePendingResult.setResult(Unknown Source:131)
> E/Error (13343): at com.google.android.gms.auth.api.signin.internal.zzj.zzc(Unknown Source:5)
> E/Error (13343): at com.google.android.gms.auth.api.signin.internal.zzt.dispatchTransaction(Unknown Source:6)
> E/Error (13343): at com.google.android.gms.internal.auth-api.zzd.onTransact(Unknown Source:12)
> E/Error (13343): at android.os.Binder.execTransactInternal(Binder.java:1021)
> E/Error (13343): at android.os.Binder.execTransact(Binder.java:994)
> I/flutter (13343): PlatformException(error, 4: 4: , null)

@co-in  if you solved the error please add here brother.

**Comment by Abedalkareem** [comment]
Can you please check this tutorial?
https://itnext.io/how-to-integrate-gamekit-and-google-play-services-flutter-4d3f4a4a2f77

also please make sure to update the plugin to ```0.2.10```

**Comment by msarkrish** [comment]
@Abedalkareem  bro,  i integrated by above article only bro. I implemented all the things mentioned in the above article.
In manifest file added two metadata and replaced appid in first metadata.
Added new game in Google play console.
Added debug key for my application bro.
Added games_services: 0.2.10 bro.

**Comment by Abedalkareem** [comment]
can you share your app manifest here?

**Comment by msarkrish** [comment]
@Abedalkareem bro, i added Manifest file.
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.krishna.app">
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="app_name"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
            <meta-data
    android:name="com.google.android.gms.games.APP_ID"
    android:value="****************" />

<meta-data
    android:name="com.google.android.gms.version"
    android:value="@integer/google_play_services_version" />
    </application>
</manifest>

**Comment by Abedalkareem** [comment]
Can you check if the key the app signed with is the same as you kept on google play console?
check here please, and make sure also the package id is the same
https://stackoverflow.com/questions/27609442/how-to-get-the-sha-1-fingerprint-certificate-in-android-studio-for-debug-mode

**Comment by msarkrish** [comment]
@Abedalkareem  I Checked bro, Debug SHA is same. 
I have one doubt bro, Whether i need generate release SHA and link that with Google play Console Game Services in Linked apps Tab?

**Comment by Abedalkareem** [comment]
please try this solution
https://github.com/flutter/flutter/issues/33393#issuecomment-510395178

**Comment by Pielgrin** [comment]
Hello @msarkrish have you found a solution to fix this problem ?

**Comment by xuanlocle** [comment]
After spending hours trying to figure out why android wouldn't work, it was because you instructed us to put the app id directly into the AndroidManifest.xml file instead of adding it through a string variable.
Add this in AndroidManifest.xml:
```
<meta-data android:name="com.google.android.gms.games.APP_ID" android:value="@string/game_services_project_id"/>
```

And then create a strings.xml file here:
```
<!-- res/values/strings.xml -->
<resources>
<string translatable="false" name="game_services_project_id">123456788888</string>
</resources>
```
