### ISSUE TITLE
google play Login bug

### ISSUE THREAD

**Issue by wengxianxun** [Abedalkareem/games_services#22]
I/silentSignIn( 7639): error
E/FA      ( 7639): Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
E/flutter ( 7639): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Something went wrong Status{statusCode=SIGN_IN_REQUIRED, resolution=null}, null)
E/flutter ( 7639): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 7639): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 7639): <asynchronous suspension>
E/flutter ( 7639): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 7639): #3      GamesServices.signIn (package:games_services/games_services.dart:51:29)
E/flutter ( 7639): #4      _PageIndexState.getGameCenterTest.<anonymous closure> (package:tetris/panel/page_index.dart:83:56)
E/flutter ( 7639): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:931:19)
E/flutter ( 7639): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1018:38)
E/flutter ( 7639): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 7639): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:522:11)
E/flutter ( 7639): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter ( 7639): #10     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
E/flutter ( 7639): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
E/flutter ( 7639): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter ( 7639): #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter ( 7639): #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 7639): #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)

**Comment by Abedalkareem** [comment]
It's very clear what is the issue and it's mentioned in the error.

I believe you forgot to add the app id.

```
<meta-data
    android:name="com.google.android.gms.games.APP_ID"
    android:value="your_app_id" />
```
