### ISSUE TITLE
Show native feedback for achievement unlocking

### ISSUE THREAD

**Issue by MrCsabaToth** [Abedalkareem/games_services#27]
I'm speaking for Android port right now, I haven't tried with the Apple ecosystem yet. But on Android sign-in and Leaderboard show action both able to utilize the native Android companion overlays over the Flutter UI. It'd provide further platform native user experience if the achievement unlock would also display the same type of native feedback. If that cannot be done then we'd need the #8 so we could check if the achievement is already unlocked so we could show a Flutter based unlock overlay only when it's needed. But I'd prefer the native overlay. Maybe something is blocking that in my app?
https://play.google.com/store/apps/details?id=com.dealoround.android
https://github.com/DealORound/Deal-O-Round

**Comment by MrCsabaToth** [comment]
Possibly native overlay feedback for the score submission as well.

**Comment by Abedalkareem** [comment]
@MrCsabaToth 
Please check and if the issue fixed please close the issue.
Thank you.

**Comment by MrCsabaToth** [comment]
> @MrCsabaToth
> Please check and if the issue fixed please close the issue.
> Thank you.

Wow, you did a ton of work!!!
For some reason the signIn works in my dev environment, but I can only test the rest on the release versions. So I'll need to roll out a release (this was like that with other versions as well BTW, nothing new).

**Comment by MrCsabaToth** [comment]
@Abedalkareem the new release of my game rolled out and I could confirm with a test on that release that the achievement unlock native feedback is working!
