### ISSUE TITLE
Feauture Request: Get leaderboard by id for Android

### ISSUE THREAD

**Issue by ScripterScript** [Abedalkareem/games_services#29]
Hi,
first of all thank you very much for creating this awesome plugin :)
Could you please add the feauture that android users can also get a specific leaderboard by id as it is for iOS right now?
That would make it easier for users to take a look at specific leaderboards instead of seeing the whole table.

Thank you
Have a nice day!

**Comment by wlw81** [comment]
yes, this would be great!
