### ISSUE TITLE
Please upgrade to flutter 1.12

### ISSUE THREAD

**Issue by zxzx74147** [Abedalkareem/games_services#3]
On Android：
MissingPluginException(No implementation found for method silentSignIn on channel games_services)

Supporting the new Android plugins APIs：
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

Thanks!

**Comment by dioxmio** [comment]
that would be cool, any plans on doing this?

**Comment by Abedalkareem** [comment]
Hi,
Sorry for the delay I published a new version with the upgrade. I'll close the issue and if you face any issue please reopen it or create new one.
Thank you!
