### ISSUE TITLE
Feauture Request: Get leaderboard data

### ISSUE THREAD

**Issue by gadgetreviews** [Abedalkareem/games_services#33]
Hello,

Thanks for this great plugin. 

I want to make a leaderboard inside my game. But ```GamesServices.showLeaderboards();``` makes a pop up and shows the leaderboard out of my game. If I can retrieve the leader board data inside my flutter code, I can build my own leaderboard inside my game, natively.

Thanks for help

**Comment by Abedalkareem** [comment]
This has been added with this pull request:

https://github.com/Abedalkareem/games_services/pull/83

Thanks!
