### ISSUE TITLE
Error when calling signin (IncompatibleClassChangeError)

### ISSUE THREAD

**Issue by rafagan** [Abedalkareem/games_services#37]
When I call `GamesServices.signIn()`, the following error occurs:

`
E/AndroidRuntime(26341): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.games.GamesClient, but class was expected (declaration of 'com.google.android.gms.games.GamesClient' appears in /data/app/~~7iqBC3K6nKN7aJbMGXjczw==/com.kolbapps.drumtiles-zkF175vOaZriZctzZsoTMw==/base.apk)
E/AndroidRuntime(26341): 	at com.abedalkareem.games_services.GamesServicesPlugin.handleSignInResult(GamesServicesPlugin.kt:85)
E/AndroidRuntime(26341): 	at com.abedalkareem.games_services.GamesServicesPlugin.silentSignIn$lambda-0(GamesServicesPlugin.kt:60)
E/AndroidRuntime(26341): 	at com.abedalkareem.games_services.GamesServicesPlugin.lambda$5eqX61qP7rtF7VtNF6jsoHjn9yY(Unknown Source:0)
E/AndroidRuntime(26341): 	at com.abedalkareem.games_services.-$$Lambda$GamesServicesPlugin$5eqX61qP7rtF7VtNF6jsoHjn9yY.onComplete(Unknown Source:4)
E/AndroidRuntime(26341): 	at com.google.android.gms.tasks.zzj.run(com.google.android.gms:play-services-tasks@@17.2.0:4)
E/AndroidRuntime(26341): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(26341): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(26341): 	at android.os.Looper.loop(Looper.java:246)
E/AndroidRuntime(26341): 	at android.app.ActivityThread.main(ActivityThread.java:8506)
E/AndroidRuntime(26341): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26341): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(26341): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
`

Any help?

**Comment by AllanKlaus** [comment]
Just trying to help. I'm not using this lib but I was gotting the same error using one lin with React Native. I solved it fixing the verios of play-service-games and play-services-auth on my build.grandle file.

```
implementation 'com.google.android.gms:play-services-games:17.+'
implementation 'com.google.android.gms:play-services-auth:17.+'
```

When I got this erro I was using the version the latest version. Maybe this can help you.

**Comment by Abedalkareem** [comment]
Hi @rafagan,

We updated the play services to the latest can you try now.

Also, you can check this:
https://stackoverflow.com/questions/591411/java-error-found-interface-but-class-was-expected

If you still have an issue, you can create a new issue or reopen this issue.
