### ISSUE TITLE
[Feature request] Get scores of leaderboard

### ISSUE THREAD

**Issue by tssmobile** [Abedalkareem/games_services#38]
Is there a plan to release the feature that only returns the leaderboard scores for easy customizing the UI instead of the default UI?

**Comment by EliaTolin** [comment]
@Abedalkareem news?

**Comment by intercretasyo** [comment]
This would be good. I tried to tweak it to learn how can this be coded, but I really can't figure out how.

**Comment by Abedalkareem** [comment]
Duplicate of #33
