### ISSUE TITLE
I want to get the signin user's id.

### ISSUE THREAD

**Issue by Tanesan** [Abedalkareem/games_services#45]
I want to get the signin user's id.
What should I do?

**Comment by EliaTolin** [comment]
me too, any suggestions? @Tanesan @Abedalkareem

**Comment by Abedalkareem** [comment]
Hi @Tanesan @EliaTolin,

I'll try to add this feature soon.

**Comment by Abedalkareem** [comment]
Hi guys,

This feature is now available!

Please check the readme file.

Please don't forget to support this library by giving a start and sharing it.

Thanks!
