### ISSUE TITLE
How can I get the player score in the leaderboard?

### ISSUE THREAD

**Issue by lyoko515** [Abedalkareem/games_services#47]
How can I get the player score in the leaderboard?

**Comment by Eleck45** [comment]
I need this too.

**Comment by tatsuya-sagara** [comment]
I want this feature too!

**Comment by EliaTolin** [comment]
I need this me too.

**Comment by Abedalkareem** [comment]
Good idea!

I'll try to implement this whenever I have time!

**Comment by MorenoDD** [comment]
Really need this! 
Thanks!

**Comment by Abedalkareem** [comment]
Hi,

This feature was released in version 2.0.9!

Thanks!
