### ISSUE TITLE
Save and load data

### ISSUE THREAD

**Issue by Eleck45** [Abedalkareem/games_services#48]
I want to save and load game data so that I can allow the app to be used on multiple devices.  How can I do?

**Comment by tatsuya-sagara** [comment]
I too would love to have the ability to load!

**Comment by Abedalkareem** [comment]
Good idea!
I'll try to add this whenever i have time.

I'm keeping the below references for the future, or if someone wants to implement it.
Android:
https://developers.google.com/games/services/common/concepts/savedgames

iOS:
https://developer.apple.com/documentation/gamekit/gklocalplayer/1520527-savegamedata

**Comment by mgazisalik** [comment]
I didn't want to do this on my server-side so I am still waiting for this feature to be implemented :)

**Comment by jonafeucht** [comment]
Started to work on this. Follow progress: https://github.com/Abedalkareem/games_services/pull/65

**Comment by Abedalkareem** [comment]
Hi,
I had some free time the last few days so I went ahead and I created a pull request with save a game, load a game, and delete a game on android and iOS/macOS.

You can check this branch, I tested it and it's working fine.

https://github.com/Abedalkareem/games_services/pull/75

I'll try to release it maybe today or tomorrow.
Thanks!

**Comment by Abedalkareem** [comment]
These features are now available in version 2.2.0.

Thanks,

**Comment by tahatalal** [comment]
I'm getting this error when trying to use the save feature. (Must include Drive.SCOPE_APPFOLDER to use snapshots). Do you know how to fix it? @Abedalkareem.

**Comment by Abedalkareem** [comment]
@tahatalal 
You must pass `shouldEnableSavedGame` as true
```dart
 GameAuth.signIn(shouldEnableSavedGame: true);
```
