### ISSUE TITLE
Crash when calling unlock achievement 

### ISSUE THREAD

**Issue by gyuri-fluttech** [Abedalkareem/games_services#53]
I encountered the following crash:

```
E/AndroidRuntime(30536): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter it
E/AndroidRuntime(30536): 	at com.abedalkareem.games_services.GamesServicesPlugin.unlock$lambda-4(Unknown Source:7)
E/AndroidRuntime(30536): 	at com.abedalkareem.games_services.GamesServicesPlugin.lambda$kkeGD3EizKtaMlHmWz59cxTe3fc(Unknown Source:0)
E/AndroidRuntime(30536): 	at com.abedalkareem.games_services.-$$Lambda$GamesServicesPlugin$kkeGD3EizKtaMlHmWz59cxTe3fc.onSuccess(Unknown Source:4)
E/AndroidRuntime(30536): 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
E/AndroidRuntime(30536): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(30536): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(30536): 	at android.os.Looper.loop(Looper.java:233)
E/AndroidRuntime(30536): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
E/AndroidRuntime(30536): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30536): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/AndroidRuntime(30536): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

I investigated but didn't find anything. Could be something on my side ?

**Comment by jonafeucht** [comment]
Skimming over the crash log you provided, `Parameter specified as non-null is null ` which would mean that you either forgot to pass a parameter or there is something inherently wrong with `unlockImmediate` as stated in #53.

I'll have to test this on my end, but it would be great if you could provide minimal reproducible code.

**Comment by impure** [comment]
I have this issue too. It appears to be due to `.addOnSuccessListener {
      result.success("success")
    }` in `unlock()` in https://github.com/Abedalkareem/games_services/blob/1292cb1323dbd21c9ea2cd12ba7d11f39020bdae/games_services/android/src/main/kotlin/com/abedalkareem/games_services/GamesServicesPlugin.kt

When you remove it, it works fine. Strange as `.addOnFailureListener {
      result.error("error", it.localizedMessage, null)
    }` still works.

And it's not ` result.success("success")` as it still happens if you remove it.

**Comment by impure** [comment]
OK, it appears to be a known issue with recent versions of play services: https://developers.google.com/android/guides/releases#december_16_2021
It's an easy fix, just update one dependency. I made it here: https://github.com/Abedalkareem/games_services/pull/55
