### ISSUE TITLE
I just want to clarify the getPlayerID

### ISSUE THREAD

**Issue by intercretasyo** [Abedalkareem/games_services#58]
The description mention that for IOS it is unique for my game but not for other games? Also, how about Android, is it unique for everything in Android?

**Comment by Abedalkareem** [comment]
Hi,
I didn't find any information about that in the android documentation sadly.

**Comment by Abedalkareem** [comment]
For anyone looking, you can find more info here:
https://developers.google.com/android/reference/com/google/android/gms/games/PlayersClient#public-abstract-taskstring-getcurrentplayerid
