### ISSUE TITLE
Android - Work only in debug mode

### ISSUE THREAD

**Issue by EliaTolin** [Abedalkareem/games_services#59]
Hi, 

I configure all step for use GamesServices but my app works only in debug mode for android devices, but for iOS works correctly in debug and release mode.
For use this plugin in release need configure other steps?

Here you find repository of my app:
https://github.com/EliaTolin/infinity_sweeper

**Comment by Abedalkareem** [comment]
Hi,
Yes for release build you must use the sha1 generated from the release keystore.
please check here, search for sha1:
https://itnext.io/how-to-integrate-gamekit-and-google-play-services-flutter-4d3f4a4a2f77
