### ISSUE TITLE
showLeaderboards Not Working

### ISSUE THREAD

**Issue by keinou** [Abedalkareem/games_services#62]
await GamesServices.showLeaderboards(androidLeaderboardID: 'CgkXXXXXXXXX'), not showing nothing, but the response is "success".
D/CompatibilityChangeReporter(12922): Compat change id reported: 78294732; UID 10153; state: DISABLED

**Comment by Abedalkareem** [comment]
Hi,
I just tried it now, and it's working fine, please make sure that you are passing the correct leaderboard ID, and that there are no issues in configuring the leaderboard.

![Screenshot_1657470758](https://user-images.githubusercontent.com/14274852/178153573-d8b6272f-664d-490d-a26f-2bd9f1c493a5.png)
