### ISSUE TITLE
Android version does not work

### ISSUE THREAD

**Issue by tomatoset** [Abedalkareem/games_services#7]
> @tomatoset is this fix working ?
> 
> This didn't work on me, i deleted and re-installed the plugin, still same problem. @Abedalkareem
> 
> Edit: I have deleted android folder, updated flutter to latest version, flutter doctor seems fine. I still get the same error.

You're right the problem also remained

_Originally posted by @tomatoset in https://github.com/Abedalkareem/games_services/issues/6#issuecomment-594657083_

**Comment by Abedalkareem** [comment]
Is it the same error or different error? can you share the full log?

**Comment by mehmetuysal** [comment]
Hi @Abedalkareem 

Yes it is same error, nothing changed, here is the log

1 warning                                                               
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
/Users/mehmet/flutter_workspace/blockmaster/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:27: error: constructor GamesServicesPlugin in class GamesServicesPlugin cannot be applied to given types;
    flutterEngine.getPlugins().add(new com.abedalkareem.games_services.GamesServicesPlugin());
                                   ^                                    
  required: Activity                                                    
  found: no arguments                                                   
  reason: actual and formal argument lists differ in length            
 
```
1 error                                                                 
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileReleaseJavaWithJavac'.           
> Compilation failed; see the compiler error output for details.        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 44s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      46.3s
Gradle task assembleRelease failed with exit code 1
```

**Comment by Abedalkareem** [comment]
@mehmetuysal @tomatoset 
This issue fixed by @alexeystrakh (https://github.com/Abedalkareem/games_services/issues/12)
Can you please try again?
