### ISSUE TITLE
Migrate Play Games Services v2

### ISSUE THREAD

**Issue by Abedalkareem** [Abedalkareem/games_services#77]
On March 15, 2022, Google Play Games Services v2 was released which has a simplified sign-in functionality that requires very less work compared to the current implementation.

**Comment by moshOntong-IT** [comment]
is this still under develop?

**Comment by egonbeermat** [comment]
Any updates on this feature?

**Comment by egonbeermat** [comment]
Is this package abandoned?

**Comment by Abedalkareem** [comment]
@egonbeermat 

You can clone the project and do the migration then create a PR. If no one does it now, I'll do it once I update my Flutter game.
Before doing the migration I have to understand what will change because two months ago I was working on a native Android app and added the Games Services v2, my next step is to migrate this plugin once I update my app.

Thanks,

**Comment by egonbeermat** [comment]
Thanks for that information! This is probably too much for me to do myself given my current familiarity with plugin development and the Games Services API itself, you are much better positioned to do this, from a knowledge point of view! It's just good to know that you plan for this at some point!

**Comment by Abedalkareem** [comment]
While reading the documentation,  I discovered one challenge, We are using scopes for Saved Games so we have to use Google Sign-in alongside Play Games Services.


https://developers.google.com/games/services/android/signin#remove_extra_scopes
_With Play Games Services v2 you cannot request any additional scopes. If you still need to request additional scopes, then we recommend you use the [Google Sign In SDK](https://developers.google.com/identity/sign-in/android/start-integrating) alongside Play Games Services._

**Comment by Abedalkareem** [comment]
I created a new pull request with the changes #119 
Can you please guys try if it's working fine with your games?

Thanks!
