### ISSUE TITLE
Get information on the high score and if an achievement is unlocked

### ISSUE THREAD

**Issue by alexeystrakh** [Abedalkareem/games_services#8]
## User's High Score?

It's useful when an app was reinstalled and you want to restore the player's high score on app startup.

## Was an achievement unlocked?

It's needed when a user hits an achievement to check if it was unlocked and if it wasn't showing some UI to congratulate and unlock it with game services.

**Comment by MrCsabaToth** [comment]
Can we have native achievement unlock feedback like we have for sign-in and leaderboards? #27

**Comment by MrCsabaToth** [comment]
Note, that #27 is fixed (Android platform), so the pressure for an "is achievement unlock" is less now in case someone is fine with the native UI.

**Comment by Abedalkareem** [comment]
Hi,

This feature was released in version 2.0.9!

Thanks!
