### ISSUE TITLE
Need help with How to use images from LoadAchievements

### ISSUE THREAD

**Issue by RaulSangosto** [Abedalkareem/games_services#86]
Hello, I ve seen that it has been change the AchievementItemData images from urls to base64 strings
I ve tried this implementations https://stackoverflow.com/questions/46145472/how-to-convert-base64-string-into-image-with-flutter
but it is not working. Can anyone help me with how to implemented as Image.

Thanks!!

**Comment by Abedalkareem** [comment]
Hi!

I changed it to base64 to make it work on iOS and Android as on iOS I don't have a URL.

To show the image you can use the way below:

```dart
import 'dart:convert';
Image imageFromBase64String(String base64String) {
  return Image.memory(base64Decode(base64String));
}
```

```dart
@override
Widget build(BuildContext context) {
  return Container(
    child: imageFromBase64String(base64String),
  );
}
```

I hope this will help you!

**Comment by RaulSangosto** [comment]
Hi! Thanks for the quick response. 
I tried it but I get this error:
FormatException: Invalid character (at character 77)

**Comment by Abedalkareem** [comment]
Can you try this then

```dart
Image imageFromBase64String(String base64String) {
  return Image.memory(base64Decode(base64String.replaceAll("\n", "")));
}
```

**Comment by RaulSangosto** [comment]
This worked perfectly thank you so much!
