### ISSUE TITLE
iOS stuck after failed to authenticate

### ISSUE THREAD

**Issue by Erfa** [Abedalkareem/games_services#92]
I discovered this issue when testing on an iOS simulator that wasn't yet logged in to Game Center.

Steps to reproduce:

1. Call `await GamesServices.signIn()`.
2. The Game Center login prompt is shown. Instead of filling it out, cancel it in the top left corner.
3. Call fails with `"failed_to_authenticate"`, presumably as expected.
4. Now, call `await GamesServices.signIn()` again.

The login screen is not shown again, and the promise is never resolved. Depending on how you implement UI around this, users could be stuck in a loading spinner.

Is this just me? Am I doing something wrong? And if not, is the problem with Apple or somewhere in this plugin? Thanks!

**Comment by theLee3** [comment]
You have done nothing wrong, but it is not a "problem". It is an annoying design decision by Apple. If a user cancels the sign-in request, your subsequent calls will be ignored. Once cancelled 3 times, on app startup, all future calls to sign them in will be ignored. This is until they sign in to Game Center elsewhere on their device. You will have to design your implementation around the "feature".
