### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by moshOntong-IT** [Abedalkareem/games_services#94]
`Future<AuthCredential> getGoogleCredential() async {
  final GoogleSignIn googleSignIn = GoogleSignIn(
    signInOption: SignInOption.games,
    scopes: ['email'],
  );

  final GoogleSignInAccount googleUser = await googleSignIn.signIn().catchError((error) {
    print('Failed to sign in with Google Play Games: $error');
  });

  if (googleUser == null) {
    print('Failed to sign in with Google Play Games.');
    return Future.value(null);
  }

  final GoogleSignInAuthentication googleAuth = await googleUser.authentication;
  final credential = GoogleAuthProvider.credential(
    accessToken: googleAuth.accessToken,
    idToken: googleAuth.idToken,
  );

  return credential;
}`

I think this library should provide an AuthCredential when the user successfully login in play games service
so then we can use that AuthCredential in Firebase Authentication

**Comment by theLee3** [comment]
Play Games & Game Center authorization is generally handled separately from any game specific backend authorization, such as Firebase. I don't know of a reason why this would be necessary or suggested.

**Comment by Abedalkareem** [comment]
As @theLee3 this is not in the scope of this plugin.
